# Generated by Django 3.1.4 on 2021-01-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='image',
            field=models.ImageField(default='avathar.png', upload_to='Image/'),
        ),
    ]
