# Generated by Django 3.1.4 on 2021-01-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210108_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_room',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
