# Generated by Django 3.1.4 on 2021-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20210108_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='number',
            field=models.IntegerField(default=101, unique=True),
        ),
    ]
