# Generated by Django 3.1.4 on 2021-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210108_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='category',
            field=models.CharField(choices=[('Double Bed', 'Double Bed'), ('Single Bed', 'Single Bed'), ('Triple Bed', 'Triple Bed')], max_length=10),
        ),
    ]
