# Generated by Django 2.2.2 on 2021-01-09 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0008_auto_20210109_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Book_Room',
        ),
    ]
