# Generated by Django 2.2.2 on 2021-01-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20210109_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_details',
            name='booked',
        ),
    ]
