# Generated by Django 3.1.4 on 2021-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_upd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upd',
            name='im',
            field=models.ImageField(default='avathar.jpg', upload_to='Profile_pics/'),
        ),
    ]
